# Generated by Django 5.2.4 on 2025-12-10 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_title', models.CharField(max_length=255)),
                ('essay_text', models.TextField()),
                ('score', models.FloatField(default=0)),
                ('grammar_errors', models.IntegerField(default=0)),
                ('spelling_errors', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
